# Generated by Django 5.1.5 on 2025-01-31 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'دانشکده ها',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='نام درس')),
                ('chance', models.IntegerField(default=1, verbose_name='شانش موفقیت')),
            ],
            options={
                'verbose_name_plural': 'اساتید',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('credits', models.PositiveIntegerField(verbose_name='واحد درسی')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='App.faculty')),
                ('professors', models.ManyToManyField(related_name='professor_courses', to='App.professor')),
            ],
            options={
                'verbose_name_plural': 'کلاس ها',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=100, unique=True, verbose_name='آیدی تلگرام')),
                ('name', models.CharField(max_length=60, verbose_name='نام')),
                ('picture', models.CharField(blank=True, max_length=200, null=True, verbose_name='لینک تصویر')),
                ('code', models.CharField(max_length=9, unique=True, verbose_name='کد دانشجویی')),
                ('coin', models.IntegerField(default=0, verbose_name='تعداد سکه')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='معدل')),
                ('course', models.ManyToManyField(blank=True, related_name='students', to='App.course', verbose_name='کلاس های پاس شده')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='App.faculty', verbose_name='دانشکده')),
            ],
            options={
                'verbose_name_plural': 'دانشجویان',
            },
        ),
    ]
