# Generated by Django 5.2.8 on 2025-11-16 18:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_student_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='passed_course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='score',
        ),
        migrations.AddField(
            model_name='student',
            name='current_energy',
            field=models.IntegerField(default=0, verbose_name='مقدار انرژی فعلی'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_time_energy',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان آخرین انرژی ثبت شده'),
        ),
        migrations.AddField(
            model_name='student',
            name='term',
            field=models.PositiveIntegerField(default=1, verbose_name='ترم'),
        ),
    ]
