# Generated by Django 5.2.8 on 2025-11-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_course_student_passed_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_course',
            field=models.ManyToManyField(blank=True, related_name='currentCourse_students', to='App.course', verbose_name='کلاس های فعلی'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passed_course',
            field=models.ManyToManyField(blank=True, related_name='passedCourse_students', to='App.course', verbose_name='کلاس های پاس شده'),
        ),
    ]
