# Generated by Django 5.2.8 on 2025-11-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_student_current_course_alter_student_passed_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_course',
            field=models.ManyToManyField(related_name='currentCourse_students', to='App.course', verbose_name='کلاس های فعلی'),
        ),
    ]
