# Generated by Django 5.2.8 on 2025-11-23 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_student_current_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='current_course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='passed_course',
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='App.student')),
            ],
        ),
    ]
