# Generated by Django 5.2.8 on 2025-11-23 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_remove_student_current_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_courses', to='App.course', verbose_name='پیش نیاز'),
        ),
    ]
