# Generated by Django 5.2.8 on 2025-11-24 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_course_prerequisite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentcourse',
            options={'verbose_name_plural': 'کلاس های دانشجویان'},
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_courses', to='App.professor'),
        ),
    ]
