# Generated by Django 5.2.8 on 2025-11-24 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_studentcourse_options_studentcourse_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_courses', to='App.professor'),
        ),
    ]
