# Generated by Django 5.2.8 on 2025-11-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_studentcourse_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='telegram_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='آیدی تلگرام'),
        ),
    ]
