# Generated by Django 5.1.5 on 2025-12-05 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_student_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='chance',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='شانش موفقیت'),
        ),
    ]
